---
- name: Installing odoo from linux source
  hosts: all
  become: yes
  tasks:
    - name: Update packages
      ansible.builtin.apt:
        update_cache: yes

    - name: Running nodejs shellscript
      shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      become: yes
      args:
        chdir: /home/bharadwaj/

    - name: Installing nodejs
      ansible.builtin.apt:
        name: nodejs

    - name: Installing essential packages
      ansible.builtin.apt:
        name: build-essential

    - name: Running nodejs shellscript
      command: npm install forever -g
      become: yes
      args:
        chdir: /home/bharadwaj/

    - name: Running nodejs shellscript
      command: npm install apidoc -g
      become: yes
      args:
        chdir: /home/bharadwaj/


    
    

    

    
